### PR TITLE
removing-redundant-go-fmt

### LINKED ISSUE #115: Running both goimports and gofmt is redundant
From: https://pkg.go.dev/golang.org/x/tools/cmd/goimports

> goimports also formats your code in the same style as gofmt so it can be used as a replacement for your editor's gofmt-on-save hook.

### PR DESCRIPTION
**Pull request by nitishchauhan0022**
Removing gofmt as goimports does the work of gofmt

Fixes #115

### CODE REVIEW

**Comment by nitishchauhan0022** [comment]
@dprotaso PTAL

**Comment by kvmware** [comment]
@nitishchauhan0022 Thanks for the PR. Instead of making this change here lets break it out as per https://github.com/knative/actions/issues/104 which you assigned yourself to.

/hold don't merge, wait for it to be broke out

**Comment by dprotaso** [comment]
Can we merge this? It doesn't look like there's progress on #104

**Pull request merged**
