### PR TITLE
make linting great again

### PR DESCRIPTION
**Pull request by kvmware**
# Changes
Fixes https://github.com/knative/test-infra/issues/2392
Idea is to suggest changes before reporting anything failing.
Note: this does have a side effect where if a change is suggested and not accepted then potentially can merge things that are not linted. However, suggesting linting and not having it accepted is better than no linting. Maybe in the future we should just auto-commit the changes instead of asking the PR owner to accept the changes and leave the suggestions for things like misspell etc.

### CODE REVIEW

**Comment by kvmware** [comment]
cc @dprotaso

**Comment by kvmware** [comment]
https://github.com/kvmware/infra/pulls has some examples of it in action

**Comment by dprotaso** [comment]
This lint workflow isn't callable and is meant to lint yaml files being PR'd to this repo - hence the `on: push`

**Comment by dprotaso** [comment]
Generally I also think we should split up some of our workflows into specific GitHub 'composite' actions and then pull those into workflows

**Review by evankanderson — COMMENTED** [review]
This looks pretty awesome! Great idea!

/lgtm

**Pull request merged**
