### PR TITLE
:bug: Use regular build command instead of codeql/autobuild

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :bug: Use regular build command instead of codeql/autobuild

/kind bug

This should fix the build of kn-plugin-event, caused by https://github.com/github/codeql/issues/12010

Fixes https://github.com/knative-sandbox/kn-plugin-event/issues/258

### CODE REVIEW

**Comment by cardil** [comment]
Verified here: https://github.com/knative-sandbox/kn-plugin-event/actions/runs/4043566707/jobs/6952639100

**Review by evankanderson — COMMENTED** [review]
This is a lot more code than autobuild.

Would it make sense to just fork on the `go.work` file and otherwise call autobuild?

**Comment by evankanderson** [comment]
/lgtm
/hold


You can cancel the hold if you prefer this approach, but I didn't want it to merge it you like my suggestion above.

**Comment by cardil** [comment]
> This is a lot more code than autobuild.
> 
> Would it make sense to just fork on the `go.work` file and otherwise call autobuild?

The autobuild, even if working, doesn't take tags into account. So, using our own build is beneficial, as more code gets scanned.

**Comment by cardil** [comment]
I assume the explanation is enough to do:

/hold cancel

**Pull request merged**
