### PR TITLE
:gift: Use Knative ls-tags tool

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :gift: Use Knative ls-tags tool

/kind enhancement

Related https://github.com/knative/test-infra/pull/2995
Unblocks https://github.com/knative-sandbox/kn-plugin-event/pull/229

**Release Note**

```release-note
Use Knative ls-tags tool instead of janky scripts that fail
```

### CODE REVIEW

**Comment by cardil** [comment]
This should fix failures like: https://github.com/knative-sandbox/kn-plugin-event/actions/runs/3268584206/jobs/5375164931

**Comment by imjasonh** [comment]
FYI this seems to have broken the [Tekton Downstream e2e Test](https://github.com/knative/pkg/actions/workflows/tekton-downstream.yaml)

https://github.com/knative/pkg/actions/runs/3317533673/jobs/5480506677#step:7:542

The test is now running with allllll the tags specified, which seems to result in baffling stdlib import cycle errors -- things just weren't meant to be built with all these tags:

```
Building with tags: 386,aix,amd64,appengine,arm,arm64,blahblh,cgo,clientlogmode,codegen,compile,complex_tests,conformance,darwin,dragonfly,e2e,ec2env,examples,exclude_disk_quota,freebsd,gc,gccgo,generate,go1.1,go1.10,go1.11,go1.12,go1.13,go1.14,go1.15,go1.16,go1.17,go1.18,go1.19,go1.2,go1.4,go1.5,go1.6,go1.7,go1.8,go1.9,gofuzz,grpcgoid,ignore,illumos,include_gcs,include_oss,integration,journald,journald_compat,js,jsoniter,jsoniter_sloppy,libdm_dlsym_deferred_remove,libdm_no_deferred_remove,linux,mips,mips64,mips64le,mipsle,modhack,nacl,netbsd,never,no_lcow,no_rdt,noasm,none,noresumabledigest,openbsd,plan9,purego,race,seccomp,solaris,spiffeid_charset_backcompat,static_build,tools,windows,windows_e2e,zos
```

The last successful run of the Tekton e2e test is here: https://github.com/knative/pkg/actions/runs/3198272700/jobs/5222584998#step:7:568

and says:

```
Building with tags: conformance e2e examples 
```

cc @vdemeester @dprotaso

**Pull request merged**
