### PR TITLE
Add token field to codecov config

### PR DESCRIPTION
**Pull request by dsimansk**
# Changes

- 🐛 Add token field to codecov config

Part of the story discussed on Slack and to be discussed on Productivity WG meeting. 

This a placeholder fix if we decide to proceed with org wide `CODECOV_TOKEN` to fix coverage uploads from `main` branches.

/cc @cardil @upodroid 
/hold

### CODE REVIEW

**Comment by upodroid** [comment]
I can add an orgwide codecov token. pls send it to me via Slack

**Comment by dsimansk** [comment]
> I can add an orgwide codecov token. pls send it to me via Slack

Thanks! It seems with TOC I have the same level of permissions. So if we give it a green light, I can do it on my end.

**Comment by dsimansk** [comment]
> > I can add an orgwide codecov token. pls send it to me via Slack
> 
> Thanks! It seems with TOC I have the same level of permissions. So if we give it a green light, I can do it on my end.

@upodroid I've added the token to both orgs.

**Review by upodroid — APPROVED** [review]
LGTM

**Pull request merged**
